"""add to model User filed confirmed

Revision ID: bf3f53b76b03
Revises: 950bbb364743
Create Date: 2025-09-15 19:44:40.979953

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bf3f53b76b03"
down_revision: Union[str, Sequence[str], None] = "950bbb364743"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "confirmed", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "confirmed")
    # ### end Alembic commands ###
